{{- if and .Values.engine.secrets (not .Values.engine.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketride.fullname" . }}
  labels:
    {{- include "rocketride.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
type: Opaque
data:
  {{- range $key, $value := .Values.engine.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
