{{- if .Values.engine.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rocketride.serviceAccountName" . }}
  labels:
    {{- include "rocketride.labels" . | nindent 4 }}
  {{- with .Values.engine.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
